CREATE TABLE IF NOT EXISTS `mydb`.`PAYMENT` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)



CREATE TABLE IF NOT EXISTS `mydb`.`TRANSACTION` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` TIMESTAMP NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `titile` VARCHAR(45) NOT NULL,
  `payment` VARCHAR(45) NOT NULL,
  `price` DECIMAL NOT NULL,
  `USER_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_TRANSACTION_USER1_idx` (`USER_id` ASC) VISIBLE,
  CONSTRAINT `fk_TRANSACTION_USER1`
    FOREIGN KEY (`USER_id`)
    REFERENCES `mydb`.`USER` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)


CREATE TABLE IF NOT EXISTS `mydb`.`USER` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(90) NOT NULL,
  `password` TEXT NOT NULL,
  `is_OAuth` TINYINT NOT NULL,
  `refresh_token` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)


CREATE TABLE IF NOT EXISTS `mydb`.`USER_has_PAYMENT` (
  `USER_id` INT NOT NULL,
  `PAYMENT_id` INT NOT NULL,
  PRIMARY KEY (`USER_id`, `PAYMENT_id`),
  INDEX `fk_USER_has_PAYMENT_PAYMENT1_idx` (`PAYMENT_id` ASC) VISIBLE,
  INDEX `fk_USER_has_PAYMENT_USER1_idx` (`USER_id` ASC) VISIBLE,
  CONSTRAINT `fk_USER_has_PAYMENT_USER1`
    FOREIGN KEY (`USER_id`)
    REFERENCES `mydb`.`USER` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USER_has_PAYMENT_PAYMENT1`
    FOREIGN KEY (`PAYMENT_id`)
    REFERENCES `mydb`.`PAYMENT` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
